### ISSUE TITLE
Add NSGA-II

### ISSUE THREAD

**Issue by SigmaX** [AureumChaos/LEAP#105]
Will need:

 - A `MultiObjectiveProblem` to implement Pareto dominance
 - Non-dominated sorting & selection

**Comment by SigmaX** [comment]
Making progress.  Implemented `MultiObjectiveProblem` (with docs) for Pareto-based fitness comparisons.

Pausing here to implement part of the ZDT suite (#106 ) so I have something to write tests against.  One `MultiObjectiveProblem` is tested I'll move on to the non-dominated sorting algorithm.

![image](https://user-images.githubusercontent.com/313154/110955999-2cdbfb00-8318-11eb-98b8-8de2abf53947.png)

**Comment by markcoletti** [comment]
Taking over to (hopefully) finish implementation.

**Comment by SigmaX** [comment]
@markcoletti I'm noticing the "returns a list of fitness values" language in the docs above.  Wondering if we should update this to focus on `numpy` arrays (this issue pre-dates the shift to prefering `numpy` over lists in LEAP).

**Comment by markcoletti** [comment]
Merged in latest from `develop` to address some doctest errors.  There are still numerous warnings and odd dask related errors, which I'm going to ignore for now because those are outside the scope of this task.  We will, however, need to ensure there are tasks for those problems so that we can appropriately address them.

**Comment by markcoletti** [comment]
Changed some function signatures for clarity and added a few tactical comments. Also removed an artifact from a bum git merge.

**Comment by markcoletti** [comment]
Sub-issues:

- [ ] create sub-package `multiobjective`
- [ ] move `Problem` classes/functions to that sub-package (and anything else that should go there)
- [ ] create `mulitiobjective.ops.fast_nondominated_sort()`
- [ ] create `crowding_distance_calc()`
- [ ] create `sort_by_dominance()`

Of course there should be test harnesses for each of the new operators.  Also, unit tests for the new `Problem` classes.

**Comment by markcoletti** [comment]
- [ ] check with other EA MO packages

**Comment by markcoletti** [comment]
Have a candidate and working on jupyter notebook to shake out the bugs.  Once the bugs are sorted, the notebook should serve as an example for use.

**Comment by markcoletti** [comment]
So, we have our first run of NSGA-II:

```
[(100.27497227543383,
  111.73767919783755,
  10055.070064839023,
  12042.358235727508),
 (100.29327533301779,
  111.51318802203491,
  10058.741077024515,
  11993.13835074957),
 (99.92863176092513,
  111.09167007154431,
  9985.731445610574,
  11900.992478998678),
```

Those are just a few individuals.  And, sadly, they show that we're clearly *maximizing* when we should be *minimizing*.  I hope for this to be a simple fix.

I also observe that this run took a lot longer than I expected, so I fear some inefficiencies are lurking.

**Comment by markcoletti** [comment]
I may have fixed the problem by inverting the key criteria in the final truncation selection.  Mea culpa!  

In any case, we *may* now have a viable candidate.  Need to clean up the notebook and set things up for a review by others.

**Comment by lukepmccombs** [comment]
Looking to use this myself, and I've found the probable reason for your issue.
In `__init__` of `MultiObjectiveProblem`, `np.negative(ones, where=maximize)` does not have the desired behavior. `where` requires the `out` parameter to be set otherwise it returns uninitialized junk data where false. As SCH is a minimization problem, both coefficients would be completely random.

Using `np.where(maximize, 1, -1)` has the desired result without the above issue.

https://numpy.org/doc/stable/reference/generated/numpy.negative.html

**Comment by markcoletti** [comment]
> Looking to use this myself, and I've found the probable reason for your issue. In `__init__` of `MultiObjectiveProblem`, `np.negative(ones, where=maximize)` does not have the desired behavior. `where` requires the `out` parameter to be set otherwise it returns uninitialized junk data where false. As SCH is a minimization problem, both coefficients would be completely random.
> 
> Using `np.where(maximize, 1, -1)` has the desired result without the above issue.
> 
> https://numpy.org/doc/stable/reference/generated/numpy.negative.html

Thanks, @lukepmccombs , I'll make that change ASAP!

**Comment by markcoletti** [comment]
@lukepmccombs , I made your fix and that appeared to do the trick: we now have a proper Pareto front. I'm still a little wary of some of the implementation, but hopefully some additional tests that more thoroughly vet multiobjective behavior will put me at ease.

I still need to write documentation for this and to run the other MO benchmarks, but I'm calling this done.  I hope others kick the tires on the NSGA-II implementation.

**Comment by SigmaX** [comment]
@markcoletti This exchange tips me off to the fact that we don't have unit tests for `MultiObjectiveProblem`.

**Comment by markcoletti** [comment]
We do have `tests/multiobjective/ops.py`, so we have a start there.  Problem tests are next..
