### ISSUE TITLE
Pareto-front Plotting Probe for Multi-objective fitnesses

### ISSUE THREAD

**Issue by SigmaX** [AureumChaos/LEAP#106]

**Comment by markcoletti** [comment]
Started work on this.  As a side-effect may finally give some love to our readthedocs documentation, viz probes, which is very long overdue.

**Comment by markcoletti** [comment]
Created branch 106-pareto-front-plotting-probe-for-multi-objective-fitnesses for work.

**Comment by SigmaX** [comment]
Oh, I already started this, but it seems maybe never merged into `develop`?

See https://github.com/AureumChaos/LEAP/commit/16e9da1cc8f90dd3f3375dfc12056c63d07c557b

**Comment by markcoletti** [comment]
@SigmaX I'll merge your changes into my current dev branch and poke at what you've done so far.

**Comment by SigmaX** [comment]
@markcoletti Appreciate it!

**Comment by markcoletti** [comment]
This has been completed, merged into `develop`, and consequently was part of the 0.9 release.  Closing.
