### ISSUE TITLE
MVP 6: Parallel Fitness Evaluation

### ISSUE THREAD

**Issue by SigmaX** [AureumChaos/LEAP#11]
Use `dask` to parallelize fitness evaluation, at least for simple generational EAs.

**Comment by piprrr** [comment]
I'll be bringing over the distributed, parallel evals from `smallLEAP`, and then updating.

**Comment by piprrr** [comment]
I've successfully ported over the `smallLEAP` implementation, which is now in `leap.parallel`.  I've also brought over the example, which is in `examples`, of course.

There may be some significant refactoring to be done with this design.  In particular, inspired by @SigmaX 's monolithic functions, I may want to take a similar approach here.  That is, I use a class when I can probably have a big ole function do everything, instead.

Something to discuss for the next scrum.
