### ISSUE TITLE
simple.py missing probe import

### ISSUE THREAD

**Issue by grudloff** [AureumChaos/LEAP#110]
Hello! Just getting to know the package and found a small problem on `simple.py`. It seems the probe module is not imported making `ea_solve()` break when `viz==True`.

By the way, I like where this package is going. Keep up the good work!

**Comment by piprrr** [comment]
@grudloff , thank you for bringing this to our attention!  Hopefully will fix this this weekend.

CC: @SigmaX

**Comment by SigmaX** [comment]
Fixed on `develop`, with unit test to prevent similar bitrot in the future.  Will be in v0.6.0.
