### ISSUE TITLE
Distributed evaluation only works with DistributedIndividual

### ISSUE THREAD

**Issue by SigmaX** [AureumChaos/LEAP#126]
The purpose of `DistributedIndividual` is to support extra attributes like `start_time` and `is_viable`.

If you don't want this information, it should be possible to perform distributed evaluation with regular `Individual`s.

Currently, trying this produces this error:

```
  File "/home/eric/repos/LEAP/leap_ec/distributed/evaluate.py", line 52, in evaluate
    if not individual.is_viable:
AttributeError: 'Individual' object has no attribute 'is_viable'
```

**Comment by piprrr** [comment]
`is_viable` is added in `leap_ec.individual.RobustIndividual`, but the original need still stands.

**Comment by SigmaX** [comment]
Ah, thanks for the clarification.  I see now that `DistributedIndividual` inherits from `RobustIndividual`.

**Comment by SigmaX** [comment]
Fixed with a simple `hasattr()` check.
