### ISSUE TITLE
Individual with interindividual operations 

### ISSUE THREAD

**Issue by grudloff** [AureumChaos/LEAP#128]
Since you are going to be using numpy genome representations as suggested by issue #109, I think an Individual with interindividual genome operations built-in would be really useful for EAs like differential evolution or particle swarm optimization. 
Here is an example with most operations I could think of. It also gives the flexibility to accept operations with constants thanks to `getattr` defaulting to the object when there is no genome attribute.

```python
class Individual_op(Individual):
    '''Individual with interindividual genome operations'''
    def __init__(self, genome, decoder=None, problem=None):
        super().__init__(genome, decoder, problem)

    def __iadd__(self, other):
        self.genome += getattr(other, 'genome', other)
        return self
    
    def __add__(self, other):
        individual = self.clone()
        individual += other
        return individual

    def __isub__(self, other):
        self.genome -= getattr(other, 'genome', other)
        return self

    def __sub__(self, other):
        individual = self.clone()
        individual -= other
        return individual

    def __imul__(self, other):
        self.genome *= getattr(other, 'genome', other)
        return self

    def __mul__(self, other):
        individual = self.clone()
        individual *= other
        return individual
    
    __rmul__ = __mul__
    
    def clip(self, bounds):
        self.genome = self.genome.clip(*bounds)
        return self
```

**Comment by piprrr** [comment]
One of the overriding principles for LEAP is loose-coupling, so a lot of this functionality will be found in pipeline operators.  For example, the `clip()` member function will be implemented as a pipeline operator.  This also facilitates addressing newrepresentation-specific features by moving these semantics to pipeline operators.  I.e., we will likely implement the`numpy` representation just as we have done for integer, binary, and real-value representations in that there will be a separate sub-package for that along with representation-specific operators.

But, thanks for sharing this as I can see these member functions being encapsulated as pipeline operators for easy mixing.

**Comment by SigmaX** [comment]
Thanks for the idea, @grudloff !

I'm thinking the same as @piprrr .  I can see the appeal of having syntactic sugar for doing vector operations on individuals.  And we already do something similar for fitness comparison (via `__lt__()`, for instance).  But so far we've managed to avoid putting representation-specific logic in `Individual`, or more generally spreading out logic into subclasses of it.

One could, of course, define a `PSOIndividual` or such, and use it with special PSO operators that know about the syntactic sugar.  Just having PSO operators that know how to add genomes (and expect `numpy` genomes) would keep all that logic in one place, however.
