### ISSUE TITLE
`ea_solve` should respect hard bounds

### ISSUE THREAD

**Issue by SigmaX** [AureumChaos/LEAP#135]
`ea_solve()` takes a `bounds` parameter, but it currently only uses it to define the bounds of the _initial population_.

This violates the "principle of least surprise," since it's natural for a user to assume that "`bounds`" are respected throughout the optimization process.

**Comment by piprrr** [comment]
This should be toggelable behavior since sometimes it's desirable to allow individuals to wander off the reservation.  But, yes, the default should be to respect the bounds.

**Comment by SigmaX** [comment]
Done—there's now a `hard_bounds` Boolean parameter on `ea_solve()` which defaults to `True`.

**Comment by aymericvie** [comment]
Amazing, thank you very much!
