### ISSUE TITLE
Migrate Travis-CI.org

### ISSUE THREAD

**Issue by SigmaX** [AureumChaos/LEAP#141]
Travis-CI.org is being merged with Travis-CI.com, and the former will be shut down and rendered read-only eventually.

We have to migrate the repo over to a Travis-CI.com account manually.

**Comment by SigmaX** [comment]
This is now  urgent, as Travis-CI.org has gone read-only as of June 15th.

**Comment by SigmaX** [comment]
Took at stab at this, but I think only @AureumChaos is able to migrate it over.

The instructions are [here](https://docs.travis-ci.com/user/migrate/open-source-repository-migration), but unnecessarily complicated and seems to be written by laweyers.

I think it's as simple as signing up at travis-CI.com by linking your GitHub account, then clicking the "migrate" tab to bring the LEAP test run config over from travis-CI.org.

**Comment by SigmaX** [comment]
I think we want to nip the root problem here, by setting up co-ownership of the LEAP repo.  See #159

**Comment by markcoletti** [comment]
Luke has set up github actions for our CI pipeline, thus making this irrelevant.  Closing.
