### ISSUE TITLE
Elitism for minimization problems appears to be broken.

### ISSUE THREAD

**Issue by markcoletti** [AureumChaos/LEAP#189]
While working on a test minimization problem for Gremlin, I got the following population with an elitism of 2:

```
step,fitness,genome
0,0.9991189427312775,[1]
0,0.9843423799582464,[6]
0,0.9922178988326849,[7]
0,0.9844961240310077,[2]
0,0.996938775510204,[0]
0,0.9876681614349776,[5]
0,0.526694045174538,[8]
1,0.9801783944499505,[9]
1,0.9991189427312775,[1]
1,0.998019801980198,[3]
1,0.9991189427312775,[1]
1,0.998019801980198,[3]
1,0.9922178988326849,[7]
1,0.9991189427312775,[1]
2,0.9843423799582464,[6]
2,0.526694045174538,[8]
2,0.9876681614349776,[5]
2,0.996938775510204,[0]
2,0.9876681614349776,[5]
2,0.996938775510204,[0]
2,0.526694045174538,[8]
3,0.996938775510204,[0]
3,0.9991189427312775,[1]
3,0.998019801980198,[3]
3,0.9843423799582464,[6]
3,0.9844961240310077,[2]
3,0.9876681614349776,[5]
3,0.9922178988326849,[7]
4,0.996938775510204,[0]
4,0.996938775510204,[0]
4,0.9922178988326849,[7]
4,0.9876681614349776,[5]
4,0.998019801980198,[3]
4,0.9876681614349776,[5]
4,0.9959266802443992,[4]
```
When `[8]` first appears, it is an "elite" that should remain visible for the rest of the run, but doesn't.

**Comment by markcoletti** [comment]
This may be an issue with *when* I'm printing the population.  Checking.

**Comment by markcoletti** [comment]
This is profoundly disturbing.  I cannot find the test harness for `ops.elitist_survival()` and I'm pretty sure there was one.

**Comment by markcoletti** [comment]
Turned out to be a non-issue.  Sorta.

I had inserted a population probe as the last pipeline operator passed to `generational_ea`.  However, even though *I* specified it as the last operator it was, in fact, not the last operator.  The elitism survivor operator is the last operator, which means I was getting a population snapshot of just the offspring before elitism was applied.  Which meant that each population that was printed to the CSV file only included the offspring per generation sans elites.  And for a moment that mislead me to believe there was a problem with elitism.

**Comment by SigmaX** [comment]
@markcoletti Oh that's a good observation.  I may have observed the same thing a few weeks ago, thinking "hey, my best-of-gen fitness curve should be monotonic with elitism, why isn't it?!"—but I didn't have time to investigate at the time.
