### ISSUE TITLE
Merge existing develop branch into legacy, and (carefully!) clear the develop branch

### ISSUE THREAD

**Issue by piprrr** [AureumChaos/LEAP#2]
'legacy' already exists and contains LEAP 1.0. We'll be starting from a clean slate moving forward, so the first step is to "reset" `develop`, and then set it up for a proper python package environment.

**Comment by piprrr** [comment]
`develop` cleaned out, and minimal set of functionality brought over from `smallLEAP`.

**Comment by SigmaX** [comment]
@AureumChaos, IIRC we found that the `develop` branch already existed and differed from `master` when we started talking LEAP 2.0.

You wanna check and make sure that reseting `develop` didn't undo something that was important for your purposes?

**Comment by piprrr** [comment]
I have reverted my changes and have moved this task back to 'doing.'
