### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by SigmaX** [AureumChaos/LEAP#214]
Cruft in our branch list.

**Comment by markcoletti** [comment]
I've been doing some weeding wrt branches, though this may be an ongoing "branch gardening" activity.

**Comment by markcoletti** [comment]
@SigmaX , giving this a bump.  This weeding operation sounds like an excellent thing we can knock out next time we're in a LEAP scrum together.

**Comment by SigmaX** [comment]
@markcoletti Appreciate it!

I deleted a few branches that had already been merged and most of my stale branches, and merged one that had just tiny changes.

All of these look like they could be safely deleted as well—care to confirm?:

![image](https://github.com/AureumChaos/LEAP/assets/313154/b66c5eeb-2758-4326-82aa-dfee6f612fdf)

**Comment by markcoletti** [comment]
Yep!  I think those can be cleaned up.

**Comment by SigmaX** [comment]
Went ahead and deleted those (since I couldn't think of any way they could still be needed), and two more of yours that had already been merged (and their issues closed).

We're clean now!  Just four branches:

![image](https://github.com/AureumChaos/LEAP/assets/313154/9c0d9385-75f6-4d59-aaff-a1d33f1ecf1b)
