### ISSUE TITLE
Convert monolithic functions from generators to functions that return final pop.

### ISSUE THREAD

**Issue by SigmaX** [AureumChaos/LEAP#225]
The "algorithms are iterators" pattern we are using is confusing and not really useful.

We're not using this pattern for NSGA-II: instead we'll return the final population directly.

Our other metaheuristic functions should do the same.

Checklist:
 - [x] `generational_ea` interface
 - [x] `random_search` interface
 - [x] `multipopulation_ea` interface

**Comment by SigmaX** [comment]
Picking this up and adding to the coevolution milestone because doing it will make it easier to write unit tests that are needed for #168.

**Comment by markcoletti** [comment]
IIRC, from the last scrum, I'll be taking over ownership of this.  👍

**Comment by markcoletti** [comment]
@SigmaX there doesn't appear to be an active branch associated with this task, so I'll create one using the spiffy new github "create branch for this issue" functionality.  Hopefully this will be a short-lived branch.

**Comment by markcoletti** [comment]
`random_search()` done.  The only thing to use it is the CGP stuff, and I made sure that worked ok.

**Comment by SigmaX** [comment]
Great.  Yeah, I believe I merged in the `generational_ea` stuff already, so there was no branch at the time of the hand-off.

**Comment by markcoletti** [comment]
`multipopulation_ea` now converted to return populations. All dependent code updated accordingly.  As a bonus, the associated test function now works.
