### ISSUE TITLE
Sort by rank for crowding distance

### ISSUE THREAD

**Issue by SigmaX** [AureumChaos/LEAP#226]

**Comment by markcoletti** [comment]
We had briefly discussed a quick way to do this using `toolz.groupby`, and just confirmed that's the approach to use.

To wit, I created 5 `Individuals` and then randomly assigned a `rank` from [1,2].

```
[ind.front for ind in pop]
Out[10]: [1, 2, 2, 1, 2]
```

Then I used `toolz.groupby` to group those individuals by rank.

```
r = toolz.groupby(lambda x: x.rank, pop)
r
Out[14]: 
{1: [Individual(None, IdentityDecoder(), None),
  Individual(None, IdentityDecoder(), None)],
 2: [Individual(None, IdentityDecoder(), None),
  Individual(None, IdentityDecoder(), None),
  Individual(None, IdentityDecoder(), None)]}
```

**Comment by markcoletti** [comment]
Just an interesting observation of the distribution of ranks for an initial population:

```
toolz.frequencies(ranks)
Out[3]: 
{1: 18,
 49: 2,
 82: 2,
 61: 2,
 77: 2,
 19: 2,
 18: 2,
 68: 2,
 106: 1,
 80: 1,
 110: 1,
 27: 2,
 56: 2,
 36: 2,
 39: 2,
 28: 2,
 67: 2,
 63: 2,
 45: 2,
 26: 2,
 7: 2,
 76: 2,
 41: 2,
 48: 2,
 9: 2,
 50: 2,
 24: 2,
 12: 2,
 71: 2,
 43: 2,
 2: 2,
 69: 2,
 53: 2,
 98: 1,
 35: 2,
 109: 1,
 102: 1,
 57: 2,
 81: 1,
 51: 2,
 94: 1,
 93: 1,
 23: 2,
 66: 2,
 103: 1,
 32: 2,
 88: 1,
 75: 2,
 96: 1,
 14: 2,
 33: 2,
 79: 1,
 64: 2,
 38: 1,
 22: 2,
 70: 2,
 97: 1,
 72: 2,
 15: 2,
 91: 1,
 100: 1,
 78: 2,
 58: 2,
 105: 1,
 40: 2,
 17: 2,
 47: 2,
 16: 2,
 60: 1,
 95: 1,
 55: 2,
 90: 1,
 85: 1,
 5: 2,
 25: 2,
 10: 2,
 101: 1,
 92: 1,
 21: 2,
 42: 2,
 8: 2,
 6: 2,
 86: 1,
 65: 2,
 11: 2,
 62: 2,
 20: 2,
 3: 2,
 73: 2,
 52: 2,
 37: 2,
 104: 1,
 84: 1,
 30: 2,
 107: 1,
 54: 2,
 4: 2,
 13: 2,
 83: 1,
 87: 1,
 59: 2,
 31: 1,
 99: 1,
 46: 2,
 29: 2,
 74: 1,
 44: 2,
 89: 1,
 108: 1,
 34: 1}
```

**Comment by markcoletti** [comment]
This suggests checking to see if the crowding calc by rank gets just one or two individuals, just set their distance to `inf` and call it a day.  'cause that's what's gonna happen anyway.

**Comment by markcoletti** [comment]
I'm tweaking the new jupyter notebook created by Luke Mccombs to do the comparison between the new fast rank sorting algorithm and the legacy NSGA-II version.  Having issues running the multiprocessing stuff on my laptop as denoted by this:

https://stackoverflow.com/questions/41385708/multiprocessing-example-giving-attributeerror

**Comment by markcoletti** [comment]
I swapped over to using threads instead of processes, but now fear I'm at the mercy of the GIL, so not getting the full performance I want.    According to the above stackoverflow I can install yet another 3rd party package, `multiprocess`, that uses `dill` instead of `pickle` to work around this problem, but I don't want to add yet another dependency.  Will probably jut move those functions to a separate module and import that per the article.

**Comment by markcoletti** [comment]
After much tweaking got the final plot to work, and it didn't take hours, as would have with the original configuration.  Still tells the story that the new ranked sorting is significantly faster.

**Comment by markcoletti** [comment]
With the fix of the crowding distance test, this is free to move on.  Closing.

**Comment by markcoletti** [comment]
I did a merge from `develop` to capture Luke Mccomb's changes to ensure that this didn't break anything.  All multiobjective tests still pass, so will merge and close this branch into `develop`.
