### ISSUE TITLE
Support for asynchronous NSGA-II

### ISSUE THREAD

**Issue by markcoletti** [AureumChaos/LEAP#249]
(This is different than "Allow for option of using Dask for NSGA-II," but these might be consolidated into a single task.)

Given problems that have long evaluation times for which the initial population may have a large number of non-viable individuals (such as through randomly generated DL architectures), the by-generation approach of NSGA-II is not efficient.  That is, an asynchronous steady-state EA will be able to grind through a large number of candidates until all workers are busy evaluating viable candidates, however NSGA-II will get stuck slowly finding viable candidates.  Worse yet, work cannot proceed to the next generation until all individuals are evaluated, so if there is just one viable individual and all the rest are non-viable, then the computation resources associated with the non-viable individuals will be idle until the next generation.

**Comment by lukepmccombs** [comment]
This paper may be a good starting point for an asynchronous NSGA-II variant.
https://arxiv.org/abs/1804.05208

**Comment by markcoletti** [comment]
Moving this from backlog to "to do" since there is at least one project at ORNL that needs this capability.

**Comment by lukepmccombs** [comment]
I've opened a pull request #264 with a candidate for this. It performs pretty well, but I want some eyes on it to be certain everything is working right.

**Comment by SigmaX** [comment]
Leaving open until we have an example script; that way the test harness covers this.

**Comment by lukepmccombs** [comment]
There is an example jupyter notebook that I created at the same time. If that is sufficient, then we can close this issue.

**Comment by lukepmccombs** [comment]
I'm making a quick modification to my implementation to move the Inserter out of the algorithm function so users can apply them elsewhere. This is for compatibility with gremlin, since we'll need to build it from the steady state base.

**Comment by SigmaX** [comment]
Cloasable?
