### ISSUE TITLE
Online documentation is Unavailable - Bad Request 400

### ISSUE THREAD

**Issue by TianYuanSX** [AureumChaos/LEAP#258]
https://leap_gmu.readthedocs.io/
This address is not available.

**Bad Request 400**

**Comment by SigmaX** [comment]
Hello @TianYuanSX!  

The docs URL is https://leap-gmu.readthedocs.io/ (rather than an underscore).

Did you come across somewhere in our docs/code/README that directed you the URL with a typo?

**Comment by SigmaX** [comment]
Er, [answered my own question](https://github.com/search?q=repo%3AAureumChaos%2FLEAP%20leap_gmu.readthedocs.io&type=code)—yes, we have a typo in a couple places.

**Comment by SigmaX** [comment]
Resolved.  Thanks for reporting, @TianYuanSX.

**Comment by TianYuanSX** [comment]
Cheers!
