### ISSUE TITLE
Crowding distance goes to NaN when one objective is flat

### ISSUE THREAD

**Issue by lukepmccombs** [AureumChaos/LEAP#267]
If all individuals in a rank are equal on an objective, the distance goes to NaN. This is because the scale normalization in the divisor is zero, leading to a divide by zero error. The original paper doesn't describe a solution, but my intuition is to treat it as degenerating in dimensions and just zero out that term for crowding distance.

**Comment by lukepmccombs** [comment]
This isn't an unknown aspect, but it is definitely one that hasn't been much studied. I'm going to check out some other implementations and see how they handle it.

**Comment by lukepmccombs** [comment]
Looks like PYMOO agrees with my intuition and zeros out NaNs.

https://github.com/anyoptimization/pymoo/blob/main/pymoo/operators/survival/rank_and_crowding/metrics.py#L87

**Comment by SigmaX** [comment]
Hmm—I merged the PR, and I thought the tests passed on my local, but the CI pipeline is complaining:

![image](https://github.com/AureumChaos/LEAP/assets/313154/53d53d55-a09f-41e5-8a9f-2f14db784175)

Might merit a second look?

**Comment by lukepmccombs** [comment]
I think I know what caused that, but that is another semantics thing. I believe that should be the proper behavior though, its the reference values that need updating.

Essentially, should the two "lowest" and "highest" individuals in a rank for an objective have infinite distance if that objective were flat? This especially important because those individuals would be chosen arbitrarily according to how they had been sorted. I think not, since there is no proper definition of "lower" or "higher" individuals in this situation.

In the case of this test, there are two individuals that exist alone in their rank. Thus, all objectives are zero scale and skipped.
