### ISSUE TITLE
Remove requirements_freeze.txt?

### ISSUE THREAD

**Issue by SigmaX** [AureumChaos/LEAP#274]
None of use are actually using the frozen deps file for development, and our CI pipeline is using `requirements.txt`.

The simple & honest thing to do, since we aren't maintaining `requirements_freeze.txt`, would be to remove it.

@markcoletti Any objection?

**Comment by markcoletti** [comment]
As a staunch follower of the K.I.S.S. principle, I'd be up for axing it.
