### ISSUE TITLE
PopulationMetricsPlotProbe includes data points on bounds

### ISSUE THREAD

**Issue by lukepmccombs** [AureumChaos/LEAP#276]
`PopulationMetricsPlotProbe` plots points right on the boundary of the plot. This makes the max fitness of a given run blend with the upper boundary of the plot, especially for problems that consistently hit the max fitness like CartPole. This can be fixed for all of them by improving how `PopulationMEtricsPlotProbe._rescale_ax()` works.

Matplotlib includes a couple of functions that work better for controlling the limits. `ax.relim()` recalculates data limits, `ax.update_datalim()` can add points that must be in the bounds, and `ax.autoscale_view()` will apply the changes with margins to the axes. We can replace all of our current limit overriding behavior with `ax.update_datalim()`, and use the other two functions to get the nice margin behavior that matplotlib applies to their normal plotting.

Modified version of the snippet:
```python
    def _rescale_ax(self):
        # Recalculate the limits from the data
        self.ax.relim()
        # Include the bounding points in the data lim
        self.ax.update_datalim(((self.left, self.bottom), (self.right, self.top)))
        # Autoscale the view
        self.ax.autoscale_view()
```

Before modification:
![Figure_2](https://github.com/AureumChaos/LEAP/assets/82639211/5e4225a2-4fbd-4981-91bf-1068df72b19f)

After modification:
![Figure_1](https://github.com/AureumChaos/LEAP/assets/82639211/23865e42-a1f9-4b4a-bd79-591dea1d5a20)

**Comment by lukepmccombs** [comment]
I forgot to add a comment for it, but it stopped working for me too. On my desktop, that function worked, but it didn't for my work laptop. Here is the updated function I have locally that is working:

```python
        l = min(self.left, np.min(self.x))
        r = max(self.right, np.max(self.x))

        b = min(self.bottom, np.min(self.y))
        t = max(self.top, np.max(self.y))

        self.ax.relim()
        self.ax.update_datalim(((l, b), (r, t)))
        self.ax.autoscale()
```

**Comment by lukepmccombs** [comment]
They aren't necessary, they were there to keep a hacky solution for another problem I used with the previous version of the probe. Basically, if I wanted to disable the limits I put a big positive lower bound and a big negative upper bound, which makes plotted data always the source of the limits. Without the min / max I can't do that trick. (A separate issue for a flag to disable limits is probably a good idea)

**Comment by SigmaX** [comment]
Resolved by https://github.com/AureumChaos/LEAP/commit/d15d027eb9bc335e3e0174ceafb477a03ed879ff
