### ISSUE TITLE
Fix bibtex links

### ISSUE THREAD

**Issue by markcoletti** [AureumChaos/LEAP#297]
Some of the bibtex links do not work.  E.g., links to our LEAP paper, but also to Sean Luke, Koza, etc.

**Comment by SigmaX** [comment]
Potentially related error messages I'm getting from `make doc`:

![image](https://github.com/AureumChaos/LEAP/assets/313154/38de265a-a8dd-48e5-aa36-aea48aa6701d)

**Comment by SigmaX** [comment]
The fatal one (`UndefinedEror("'style' is undefined")`) may be due to an incompatibility with sphinx 7.0, which removed the `style` key (see ex. https://github.com/kivy/kivy/issues/8230).

**Comment by markcoletti** [comment]
@SigmaX fixed this problem. Closing.
