### ISSUE TITLE
Lock in versions in requirements.txt

### ISSUE THREAD

**Issue by markcoletti** [AureumChaos/LEAP#298]
We had stripped locking dependencies to specific versions, which means installing LEAP installs the latest versions of those packages. Unfortunately, this means that from time to time a dependency will release a new version that breaks the install. So, we need to lock in on versions to work across platforms.

**Comment by markcoletti** [comment]
The trigger for this was, of course, installing LEAP on Summit.  LEAP uses `pandas`, which depends on `pyarrow`.  `pandas` updated such that it depended on installing a version of `pyarrow` that won't build on Summit out of the box.  However, if we downgrade `pandas` to 1.4.1 we resolve this problem.  (And since `pandas` isn't critical for LEAP functionality, having an older version of `pandas` won't hurt anything.)

**Comment by markcoletti** [comment]
The strategy I'm going to use is lock down the important dependencies, such as for `pandas`, and leave the others to float because they shouldn't have an impact, such as for `rich`.

**Comment by SigmaX** [comment]
Is this closed by #299 ?

**Comment by markcoletti** [comment]
> Is this closed by #299 ?

I believe so.  Closing!
