### ISSUE TITLE
Set libraries to specific versions in `requirements.txt`

### ISSUE THREAD

**Issue by piprrr** [AureumChaos/LEAP#33]
If versions are not specified, then dependent libraries will silently update to the latest version, which may occasionally break things.  E.g., a silent dependent library update breaks backward compatibility in some way, thus breaking *our* code.

**Comment by SigmaX** [comment]
Mmkay, I used `pip freeze > requirements_freeze.txt` to generate a version with pinned dependencies.

My understanding is that there's an ongoing debate within the Python community about best practices for dependency pinning (ex. with tools like `pipenv` and `poetry`)—I'm not sure what's standard these days.

My thought is that we'll manually curate a `requirements.txt` to cleanly list our top-level dependencies with minimal constraints, and periodically generate a `requirements_freeze.txt` for users.
