### ISSUE TITLE
Remove m2r dependency from docs

### ISSUE THREAD

**Issue by SigmaX** [AureumChaos/LEAP#46]
We're using the `m2r` Sphinx plugin to pull our `README.md` into the docs' "Quickstart Guide" page.  Handy.

Unfortunately, `m2r` is in archive mode, and recent updates to Sphinx have deprecated an argument that breaks people's docs builds if they use `m2r`: https://github.com/sphinx-doc/sphinx/issues/7420

We should seek an alternative, or be content to maintain a separate README and quickstart guide.

**Comment by wlievens** [comment]
Any update on this? I'm not sure how to fix my build now.

**Comment by SigmaX** [comment]
Hi @wlievens — for our project here, we're probably going to just stop using `m2r` entirely.  Looks like people over on the Sphinx thread have figured out a fix, though, so you might check out the comments there: https://github.com/sphinx-doc/sphinx/issues/7420

**Comment by wlievens** [comment]
Thanks for the info. I got it to work eventually.
