### ISSUE TITLE
MVP: Implement "Pull Model" Operators

### ISSUE THREAD

**Issue by SigmaX** [AureumChaos/LEAP#6]
Following up on https://github.com/AureumChaos/LEAP/issues/5, move the existing system over to the pull model.

**Acceptance Criteria**
 - Refactor all existing operators/probes (and existing tests) to use the new interface
 - Update the examples

**Comment by piprrr** [comment]
I'm having difficulty differentiating between this issue and #5 .  I think there's a bit of blurring here as the proposal entailed implementing things to try them out.

Should I merge the #5 branch into `develop`, and then resume work on a #6 branch?

**Comment by SigmaX** [comment]
@piprrr Whatever makes sense to you—yeah, I think the line between the two is fuzzy.  I'd be cool with a merge now.  It'd give us a chance to start playing with it while you continue!

**Comment by piprrr** [comment]
I think that makes sense.  I'll go ahead and merge, and then start a new feature branch for #6.

**Comment by piprrr** [comment]
I've started a feature branch for this `feature/issue-6`.  It's just local to my machine now, but I'll push it to `origin` before I wrap up today's work.

**Comment by piprrr** [comment]
So, for my sanity, I need to enumerate what I intend to implement for this version.  (And I prepended "MVP" to tag this as supporting a "minimally viable product.")

- [ ] truncation selection, which I'll probably steal from `smallleap`
- [ ] Gaussian mutation
- [ ] tournament selection, which I'll also nick from `smallleap`
- [ ] rename `real.py` to `real_problems.py` to be consistent with `binary_problems.py`

I think that's enough for now.  I'll resync with the rest of the crew to discuss what else needs to be done for this issue.

**Comment by piprrr** [comment]
I haven't done *all* the operators, but there should be a minimal set done, though with a binary representation only support.  I need to merge this in to `develop` so that I can get the sorely needed directory reorg sorted before proceeding with MVP epic development.
