### ISSUE TITLE
Make `is_viable` logic optional

### ISSUE THREAD

**Issue by SigmaX** [AureumChaos/LEAP#68]
Scenario: I'm working on a `Decoder` (or `Problem`), but there's a bug in my custom code that causes it to crash whenever I try and `decode` and individual—ergo, fitness evaluation _throws an exception_.

Right now, any exception during evaluation/decoding gets caught and interpreted as `is_viable = False`.

I should like to be able to disable this during development or for problems where I don't expect exceptions, so stack traces are thrown when errors occur.

![image](https://user-images.githubusercontent.com/313154/92933977-ee22c200-f414-11ea-9437-608468119ed9.png)

The obvious solution is to add a configuration flag on `Individual`.  But it's not clear how clients can set such a flag.  In our metaheueristic syntax, we currently require an `Individual` class object—there is no _instance_ of individual that we can pass parameter into.  For example:

![image](https://user-images.githubusercontent.com/313154/92934670-c4b66600-f415-11ea-95e5-52b07e64cf6e.png)

Contrast this to the `decoder` parameter of a `Representation`, which accepts an instance (such that we can pass whatever parameters we like into a decoder).

Perhaps we should consider replacing our current `individual_cls` + `initialize` scheme with, say, an `IndividualFactory`?

**Comment by piprrr** [comment]
Why not subclass `Individual` with a class called, say, `DebugIndividual` and override `evaluate()` to do what you want?

**Comment by piprrr** [comment]
I'm not averse to having a stripped down, default `Individual` with the non-viable handling logic pushed to a sub-class.  (Thus sorta inverting the class relationship I originally described.)

What should this sub-class be called that catches exceptions and assigns such individuals a NaN fitness and flags them as not being viable?

**Comment by piprrr** [comment]
Also, note that the exception is attached to the individual, and I *think* the the `Exception` object contains the file and line number of the error.

**Comment by piprrr** [comment]
Going to start work on this by creating a sub-class that has the exception handling logic.  This means by default `Individual` will fail if there is an exception thrown during evaluation.

**Comment by piprrr** [comment]
Moved exception handling to `RobustIndividual`.  Changed `leap_ec.distributerd.individual.Individual` to inherit from that class.  Changed some of the tests to use `RobustIndividual`.  Also had to change a couple examples.

Closing this out.
