### ISSUE TITLE
MVP 1a: Intro Docs

### ISSUE THREAD

**Issue by SigmaX** [AureumChaos/LEAP#7]
Draft a landing page for the Sphinx docs, explaining the gist of LEAP and its aims.

**Acceptance Criteria**
 - Pretty loose.  Be creative.

**Comment by piprrr** [comment]
I created a separate kanban board, `Documentation`, to manage this task of writing/updating documentation since it's rather onerous.

**Comment by piprrr** [comment]
This is definitely done.  Closing it.
